# Generated by Django 4.2.4 on 2023-09-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=30)),
                ('funcionarios', models.IntegerField(blank=True, null=True)),
                ('fornecedores', models.IntegerField(blank=True, null=True)),
                ('produtos', models.IntegerField(blank=True, null=True)),
                ('empresa_terceira', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_empresa',
            },
        ),
    ]
